spring.application.name: core-api
spring.profiles.active: local

spring:
  config:
    import:
      - optional:file:.env[.properties]
      - monitoring.yml
      - logging.yml
      - db-core.yml
      - supabase.yml

  web.resources.add-mappings: false

server:
  tomcat:

    max-connections: 20000
    threads:
      max: 50
      min-spare: 5
    accept-count: 100

storage:
  database:
    core-db:
      url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
      username: ${DB_USER}
      password: ${DB_PASSWORD}
  s3:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    bucket: ${S3_BUCKET}
management:
  endpoints:
    web:
      exposure:
        include: health # 또는 "*"
  endpoint:
    health:
      show-details: always
jwt:
  secret-key: "my-super-secret-key-must-be-very-long"
  issuer: "boom-api"
  access-token-expiration-seconds: 3600      # 1시간
  refresh-token-expiration-seconds: 2592000
---
spring.config.activate.on-profile: local


---
spring.config.activate.on-profile: local-dev


---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: prod



